### ISSUE TITLE
`tests` action run on multiple `working-directories` via matrix cancells all but one

### ISSUE THREAD

**Issue by addyess** [canonical/operator-workflows#219]
The error encountered:
```
Canceling since a higher priority waiting request for 'operator-workflows-Tests-tests-refs/pull/2/merge-self-hosted-false' exists
```

I believe this is because all the jobs in the matrix use the same concurrency group name

```yaml
concurrency:
  group: operator-workflows-${{ github.workflow }}-tests-${{ github.ref }}-self-hosted-${{ inputs.self-hosted-runner }}
  cancel-in-progress: true
```

recommend adding `${{ inputs.working-directory }}` as another key field here
