### ISSUE TITLE
Publishing charms from release branches check the branch-protections of the main branch

### ISSUE THREAD

**Issue by addyess** [canonical/operator-workflows#290]
The publish-charm workflow only ever checks the `main` branch for the branch protection rules, and ignores release branches.  The workflow should at least accept an alternate branch or use the branch based on the workflow event which is triggering this job:

```yaml
  branch-up-to-date-check-enabled:
    runs-on: ubuntu-22.04
    steps:
      - uses: octokit/request-action@v2.3.0
        id: get-branch-protection
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          route: GET /repos/{owner}/{repo}/branches/{branch}/protection/required_status_checks
          repo: ${{ github.event.repository.name }}
          owner: ${{ github.event.repository.owner.login }}
          branch: main       # <---------- fixed to the main branch
      - run: |
          if [ ${{ fromJson(steps.get-branch-protection.outputs.data).strict }} != "true" ]; then
            echo "::error::Strict checks are not enabled for this repository"
            exit 1
          fi
```
