### ISSUE TITLE
Missing secrets argument in `promote_charm.yaml`

### ISSUE THREAD

**Issue by yhaliaw** [canonical/operator-workflows#48]
The `secrets.CHARMHUB_TOKEN` and `secrets.GITHUB_TOKEN` secrets used in the `promote_charm.yaml` that is not defined as arguments.
https://github.com/canonical/operator-workflows/blob/main/.github/workflows/promote_charm.yaml

Can it be changed to:
```
on:
  workflow_call:
    inputs:
      origin-channel:
        type: string
        description: 'Origin Channel'
      destination-channel:
        type: string
        description: 'Destination Channel'
  secrets:
    CHARMHIB_TOKEN:
      required: true
    GITHUB_TOKEN:
      required: true
```
So it is clearer, to users the names of secrets to be passed.

Docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callsecrets

Should I create a pull request for this?
