### ISSUE TITLE
Add support for injectable matrix in integration tests

### ISSUE THREAD

**Issue by yanksyoon** [canonical/operator-workflows#71]
This issues summarises a need for adding customizable matrix parameters to the `integration test` [workflow](https://github.com/canonical/operator-workflows/blob/main/.github/workflows/integration_test.yaml)

### Problem
There is a need to support custom matrix in the integration tests, where more combinations can be required with custom parameters for integration tests that require specific/additional parameters. For example, in the current [wordpress-k8s-operator](https://github.com/yanksyoon/wordpress-k8s-operator/blob/main/.github/workflows/integration_test.yaml), additional arguments are required in the matrix as shown in the snippet below:
```yaml
matrix:
  module: [test_core, test_error, test_upgrade]
  args:
    - name: num_units=3, db_from_config
      value: "--test-db-from-config --num-units=3"
    - name: num_units=1, db_from_config
      value: "--test-db-from-config --num-units=1"
    - name: num_units=3, db_from_relation
      value: "--num-units=3"
    - name: num_units=1, db_from_relation
      value: "--num-units=1"
 ```
The wordpress-k8s operator could maintain it's own set of workflows for integration tests, however, due to the dependency of other tests on the integration test workflow, e.g. `test_and_publish_charm`, it makes it hard to use reusable workflows and maintaining the separate workflow becomes a problem when the main `operator-worlflows` diverges further.

### Proposed solution
Add an injectable JSON-based mapping under `matrix`.
```diff
strategy:
  matrix:
    series: ${{ fromJSON(inputs.series) }}
    modules: ${{ fromJSON(inputs.modules) }}
++${{ insert }}: ${{ fromJson(MATRIX_JSON) }}  
  fail-fast: false
```
MATRIX_JSON is a string that can be parsed from a file input or a json formatted string inside the workflow.
